# Generated by Django 6.0.2 on 2026-02-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='locations.temple')),
            ],
        ),
    ]
